import { BookOpen, Cookie, Droplet, Dumbbell, Flower2 } from "lucide-react";

export const dummyHabits = [
  {
    id: "workout",
    name: "Morning Workout",
    subtitle: "30 min",
    icon: Dumbbell,
    iconId: "dumbbell",
    colorId: "accent-from",
    badgeClass: "bg-accent-from/15 text-accent-from",
    days: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: "water",
    name: "Drink Water",
    subtitle: "8 glasses",
    icon: Droplet,
    iconId: "droplet",
    colorId: "accent-via",
    badgeClass: "bg-accent-via/15 text-accent-via",
    days: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: "meditate",
    name: "Meditate",
    subtitle: "10 min",
    icon: Flower2,
    iconId: "flower",
    colorId: "accent-to",
    badgeClass: "bg-accent-to/15 text-accent-to",
    days: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: "read",
    name: "Read a Book",
    subtitle: "20 min",
    icon: BookOpen,
    iconId: "book",
    colorId: "success",
    badgeClass: "bg-success/15 text-success",
    days: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: "no-sugar",
    name: "No Sugar",
    subtitle: "All day",
    icon: Cookie,
    iconId: "cookie",
    colorId: "streak",
    badgeClass: "bg-streak/15 text-streak",
    days: [0, 1, 2, 3, 4, 5, 6],
  },
];
